In [1]:
from scipy import stats
import pandas as pd
import numpy as np

In [2]:
Ci_94 = stats.norm.interval(0.94,200,30/(np.sqrt(2000)))
np.round(Ci_94,2)


array([198.74, 201.26])

In [3]:
Ci_98 = stats.norm.interval(0.98,200,30/(np.sqrt(2000)))
np.round(Ci_98,2)


array([198.44, 201.56])

In [4]:
Ci_96 = stats.norm.interval(0.96,200,30/(np.sqrt(2000)))
np.round(Ci_96,2)


array([198.62, 201.38])